@extends('layouts.app') @section('title','Dashboard') @section('content')
<div class="mb-4"><h2 class="h4 fw-bold mb-1">Good {{now()->hour<12?'morning':(now()->hour<18?'afternoon':'evening')}}, {{str(auth()->user()->name)->before(' ')}}</h2><p class="text-secondary mb-0">Here’s what’s happening with your inventory today.</p></div>
@php($cards=[['Total Products',$totalItems,'bi-box','primary'],['Total Stock In',number_format($totalInitial,2),'bi-box-arrow-in-down','info'],['Total Sold',number_format($totalSold,2),'bi-cart-check','warning'],['Remaining Stock',number_format($totalRemaining,2),'bi-layers','success'],['Total Brands',$totalBrands,'bi-tags','secondary'],['Total Categories',$totalCategories,'bi-collection','dark']])
<div class="row g-3 mb-4">@foreach($cards as [$label,$value,$icon,$color])<div class="col-sm-6 col-xl-4"><div class="card kpi-card"><div class="d-flex justify-content-between align-items-start"><div><div class="kpi-label">{{$label}}</div><div class="kpi-value">{{$value}}</div></div><span class="kpi-icon"><i class="bi {{$icon}}"></i></span></div></div></div>@endforeach</div>
<div class="row g-4 mb-4"><div class="col-xl-7"><div class="card p-3 h-100"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="section-title">Stock Movement</h2><span class="text-secondary small">Last 14 days</span></div><div class="chart-wrap"><canvas id="movementChart"></canvas></div></div></div><div class="col-xl-5"><div class="card p-3 h-100"><h2 class="section-title mb-3">Stock by Category</h2><div class="chart-wrap"><canvas id="categoryChart"></canvas></div></div></div></div>
<div class="row g-4"><div class="col-xl-5"><div class="card p-3 h-100"><h2 class="section-title mb-3">Stock by Brand</h2><div class="chart-wrap"><canvas id="brandChart"></canvas></div></div></div><div class="col-xl-7"><div class="card h-100"><div class="card-header"><h2 class="section-title">Recent Stock Activity</h2></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Product</th><th>Movement</th><th>Quantity</th><th>User</th><th>Time</th></tr></thead><tbody>@forelse($recentActivity as $activity)<tr><td class="fw-semibold">{{$activity->inventoryItem?->item_name??'Deleted product'}}</td><td><span class="badge text-bg-{{$activity->transaction_type==='SALE'?'warning':'success'}}">{{str($activity->transaction_type)->replace('_',' ')}}</span></td><td class="stock-number text-{{$activity->transaction_type==='SALE'?'danger':'success'}}">{{$activity->transaction_type==='SALE'?'-':'+'}}{{number_format($activity->quantity,2)}}</td><td>{{$activity->creator->name}}</td><td class="text-secondary">{{$activity->created_at->diffForHumans()}}</td></tr>@empty<tr><td colspan="5"><div class="empty-state py-4"><i class="bi bi-clock-history"></i>No stock activity yet.</div></td></tr>@endforelse</tbody></table></div></div></div></div>
@endsection
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/chart.js@4.5.0/dist/chart.umd.min.js"></script><script>
Chart.defaults.font.family='Inter, sans-serif';Chart.defaults.color='#667085';const grid={color:'#edf0f4'};
new Chart(document.getElementById('movementChart'),{type:'line',data:{labels:@json($movement->pluck('movement_date')),datasets:[{label:'Stock In',data:@json($movement->pluck('stock_in')),borderColor:'#2563eb',backgroundColor:'rgba(37,99,235,.08)',fill:true,tension:.35},{label:'Sales',data:@json($movement->pluck('sold')),borderColor:'#d97706',backgroundColor:'rgba(217,119,6,.06)',fill:true,tension:.35}]},options:{responsive:true,maintainAspectRatio:false,scales:{x:{grid:{display:false}},y:{beginAtZero:true,grid}},plugins:{legend:{labels:{usePointStyle:true,boxWidth:7}}}}});
new Chart(document.getElementById('categoryChart'),{type:'doughnut',data:{labels:@json($byCategory->pluck('label')),datasets:[{data:@json($byCategory->pluck('total')),backgroundColor:['#2563eb','#16a34a','#d97706','#7c3aed','#0891b2','#dc2626'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'68%',plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:7,padding:14}}}}});
new Chart(document.getElementById('brandChart'),{type:'bar',data:{labels:@json($byBrand->pluck('label')),datasets:[{data:@json($byBrand->pluck('total')),backgroundColor:'#4f79dd',borderRadius:6}]},options:{responsive:true,maintainAspectRatio:false,indexAxis:'y',scales:{x:{beginAtZero:true,grid},y:{grid:{display:false}}},plugins:{legend:{display:false}}}});
</script>@endpush
