@extends('layouts.app')
@section('title','Inventory')
@section('content')
<x-errors />
<div class="card p-3 mb-3"><form method="get" class="row g-2 align-items-end">
<div class="col-lg-3"><label class="form-label">Search</label><input class="form-control" name="search" value="{{$filters['search']}}" placeholder="Search item name or SKU"></div>
<div class="col-sm-6 col-lg-2"><label class="form-label">Brand</label><select class="form-select" name="brand_id"><option value="">All Brands</option>@foreach($brands as $brand)<option value="{{$brand->id}}" @selected($filters['brand_id']==$brand->id)>{{$brand->name}}</option>@endforeach</select></div>
<div class="col-sm-6 col-lg-2"><label class="form-label">Category</label><select class="form-select" name="category_id"><option value="">All Categories</option>@foreach($categories as $category)<option value="{{$category->id}}" @selected($filters['category_id']==$category->id)>{{$category->name}}</option>@endforeach</select></div>
<div class="col-sm-6 col-lg-2"><label class="form-label">Date</label><input class="form-control" type="date" name="date" value="{{$filters['date']}}"></div>
<div class="col-sm-6 col-lg-1"><label class="form-label">Per page</label><select class="form-select" name="per_page">@foreach([10,20,30,50,100] as $size)<option @selected($perPage===$size)>{{$size}}</option>@endforeach</select></div>
<div class="col-lg-2 d-flex gap-2"><button class="btn btn-primary">Search</button><a class="btn btn-outline-secondary" href="{{route('inventory.index')}}">Reset</a></div>
</form></div>
<div class="d-flex flex-wrap gap-2 justify-content-end mb-3"><a class="btn btn-outline-success" href="{{route('inventory.export',request()->except('page'))}}">Export Excel</a><a class="btn btn-primary" href="{{route('inventory.create')}}">+ Add Inventory</a></div>
<div class="card"><div class="table-responsive"><table class="table table-hover align-middle mb-0 inventory-table"><thead class="table-light"><tr><th>Item / SKU</th><th>Brand</th><th>Category</th><th>Initial Qty</th><th>Sold Qty</th><th>Remaining Qty</th><th>Pack Size</th>@if(auth()->user()->isSuperAdmin())<th>Purchase</th><th>Selling</th>@endif<th>Supplier</th><th>Status</th><th>Created By / At</th><th>Modify Stock</th><th>Actions</th></tr></thead>
<tbody>@forelse($items as $item)<tr><td><strong>{{$item->item_name}}</strong><br><small>{{$item->sku?:'-'}}</small></td><td>{{$item->brand->name}}</td><td>{{$item->category->name}}</td><td>{{number_format($item->quantity,2)}}</td><td>{{number_format($item->sold_quantity,2)}}</td><td>@if($item->remaining_quantity<=0)<span class="badge text-bg-danger">Out of Stock</span>@else<span class="badge text-bg-success">{{number_format($item->remaining_quantity,2)}}</span>@endif</td><td>{{$item->pack_label?:'-'}}</td>@if(auth()->user()->isSuperAdmin())<td>{{$item->purchase_price===null?'-':number_format($item->purchase_price,2)}}</td><td>{{$item->selling_price===null?'-':number_format($item->selling_price,2)}}</td>@endif<td>{{$item->supplier?:'-'}}</td><td><span class="badge text-bg-{{$item->status==='active'?'success':'secondary'}}">{{ucfirst($item->status)}}</span></td><td>{{$item->creator->name}}<br><small>{{$item->created_at->format('d-M-Y h:i A')}}</small></td>
<td><form class="d-flex gap-1 sell-form" method="post" action="{{route('inventory.sell',$item)}}">@csrf<input class="form-control form-control-sm" aria-label="Stock quantity for {{$item->item_name}}" type="number" name="sell_quantity" min="1" step="1" required><button class="btn btn-sm btn-outline-success text-nowrap" type="submit" formaction="{{route('inventory.add-stock',$item)}}">Add Stock</button><button class="btn btn-sm btn-success" @disabled($item->remaining_quantity<=0)>Sell</button></form></td>
<td><div class="d-flex gap-1"><a class="btn btn-sm btn-outline-primary" href="{{route('inventory.edit',$item)}}">Edit</a><form method="post" action="{{route('inventory.destroy',$item)}}" data-confirm="Are you sure you want to delete this item?">@csrf @method('delete')<button class="btn btn-sm btn-outline-danger">Delete</button></form></div></td></tr>@empty<tr><td colspan="{{auth()->user()->isSuperAdmin()?14:12}}" class="text-center py-4">No inventory items found.</td></tr>@endforelse</tbody></table></div></div>
<div class="mt-3">{{$items->onEachSide(1)->links()}}</div>
@endsection
